version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gitlumen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=gitlumen
      - API_PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../apps/api/src:/app/apps/api/src
      - ../packages:/app/packages
    command: yarn workspace @gitlumen/api start:dev

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api
    volumes:
      - ../apps/web/app:/app/apps/web/app
      - ../packages:/app/packages
    command: yarn workspace @gitlumen/web dev

volumes:
  postgres_data: 